AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM CloudFormation template"

Resources:
  MyIAMUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "AminCF"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

  # My IAM Group
  MyIamGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "AminGroup"

  # Attach User To Group
  UserToGroup:
    Type: "AWS::IAM::UserToGroupAddition"
    Properties:
      GroupName: !Ref MyIamGroup
      Users:
        - !Ref MyIAMUser
